/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#e4bdc0",
        "background": "#f7f9fb",
        "tertiary-container": "#00855b",
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "secondary-container": "#dae2fd",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "on-tertiary-container": "#f5fff6",
        "secondary-fixed-dim": "#bec6e0",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#5b4042",
        "surface": "#f7f9fb",
        "surface-tint": "#bd0043",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary": "#ffffff",
        "tertiary": "#006947",
        "secondary-fixed": "#dae2fd",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#ffb2ba",
        "on-tertiary-fixed": "#002113",
        "on-secondary-container": "#5c647a",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#4edea3",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#ffb2ba",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#910031",
        "primary": "#b90041",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-bright": "#f7f9fb",
        "secondary": "#565e74",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#400011",
        "primary-fixed": "#ffd9dc",
        "on-primary-container": "#fffbff",
        "primary-container": "#df2357",
        "surface-container-highest": "#e0e3e5",
        "outline": "#8f6f72",
        "surface-container": "#eceef0",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-xl": "2.25rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2.5rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-badge": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-badge": ["10px", { "lineHeight": "12px", "letterSpacing": "0.06em", "fontWeight": "700" }]
      }
    }
  },
  plugins: []
}
